# Generated by Django 4.1.4 on 2023-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_remove_items_id_items_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to='itemimages'),
        ),
    ]
