# Generated by Django 4.1.4 on 2023-09-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_alter_items_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimg', models.ImageField(upload_to='static/itemimages')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='disp_imgs',
            field=models.ManyToManyField(to='Items.displayimages'),
        ),
    ]
