# Generated by Django 4.1.4 on 2023-09-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_displayimages_items_disp_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='disp_imgs',
            field=models.ManyToManyField(blank=True, to='Items.displayimages'),
        ),
    ]
